"""add-missing-events-to-nostra-transform_events

Revision ID: cc5f9168f89a
Revises: c53651eb145e
Create Date: 2024-11-29 14:27:49.589339

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc5f9168f89a"
down_revision: Union[str, None] = "c53651eb145e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
